### PR TITLE
Native GridFS integration using GridFS bucket

### PR DESCRIPTION
**Pull request by jankapunkt**
This aims to implement the discussed native GridFS implementation from this issue: https://github.com/VeliovGroup/Meteor-Files/issues/616#issuecomment-394549311

The following has been updated:

* removed deprecated gridfs-stream
* included GridFSBucket for upload, interceptdownload and remove
* create a custom bucket `'allImages'` to show how to horizontally scale files in GridFS
* updated Person schema for background image to only accept images (using latest autoform files)
* updated documentation a lot to explain why and how to use GridFSBuckets

### CODE REVIEW

**Comment by dr-dimitru** [comment]
Great job! lgtm.
I'll run tests and wait for a few days maybe other thread members have something to say.

**Comment by jankapunkt** [comment]
Would you still be willing to merge, so I can link to this repo in the Meteor-Files documentation as a running example?

**Comment by dr-dimitru** [comment]
@jankapunkt yes, waiting to release Meteor-Files update, which is pending on some other packages and open issues/PRs. To make sure this repo works on the latest Meteor-Files release.

Thank you for this __big__ contribution

**Comment by jankapunkt** [comment]
Hey I just came back to this here, because there was an older project, where I basically hat to update to use gridFS buckets. Now I found in the meteor-files wiki an entry on 206 streaming: 
https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS---206-Streaming

it uses the old griFs-stream and should also be updated.

Could you please review and merge, if possible, so we can also resolve this issue: https://github.com/VeliovGroup/Meteor-Files/issues/616

**Comment by dr-dimitru** [comment]
@jankapunkt thank you for contribution. Merged.
Let me know if you are going to send a PR top docs

**Pull request merged**
